### ISSUE TITLE
Migrate to Flutter Infra API for retrieving Flutter SDK details and url

### ISSUE THREAD

**Issue by sampathbalivada** [sampathbalivada/flutter_installer#1]
Use the Flutter Infra releases API for retrieving Flutter SDK URL instead of a hardcoded JSON on project repo.

API URL:
[https://storage.googleapis.com/flutter_infra/releases/releases_windows.json](https://storage.googleapis.com/flutter_infra/releases/releases_windows.json)

**Comment by daffaalam** [comment]
It's very cool...
I have an idea for this, maybe you can try to see it at https://github.com/daffaalam/flutter_installer_cli, it implements Flutter and Java download API, and for `sdkmanager` you might be able to use the `sdkmanager --list` command and parsing the output
