### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by daffaalam** [sampathbalivada/flutter_installer#2]
I tried on the latest Windows 10 (1909) that was just installed.

[SDK Only]
For the first time run, Android folder is empty and stuck on the 'extracting' page. This works after running the second time.

[Full package]
Stuck on 'Installing SDK Tools' page. I think this is because it is waiting on the background to accept the licenses. https://stackoverflow.com/questions/38096225/automatically-accept-all-sdk-licences/44338806.

![Imgur](https://i.imgur.com/UGz6vXz.png)

because I have tried it several times, and I waited for more than an hour, there were no changes to Android folder, whereas when trying the manual `sdkmanager platform-tools` it was successful in a few minutes.

![Imgur](https://i.imgur.com/3OiGrwt.png)

**Comment by sampathbalivada** [comment]
Hey @daffaalam, thanks for reporting. I'll check and get back. Got a fresh install of Windows 10 too.
